### ISSUE TITLE
Question - Android TV support

### ISSUE THREAD

**Issue by yuriw** [jotyGill/openpyn-nordvpn#122]
First I'd like to say thank you for this project !  @jotyGill if I did not find this script I would not go with NordVPN, so they have to provide donations and support (I intend to let them know)!

Now I have somewhat related issue.

I was not able to setup NordVPN on Sony Android TV.  Tried stand alone OpenVPN router (https://www.amazon.com/GL-iNet-GL-AR300M16-Ext-Pre-installed-Performance-Programmable/dp/B07794JRC5/ref=sr_1_14?ie=UTF8&qid=1521928346&sr=8-14&keywords=router+openvpn) and tried OpenVPN client installed on a TV.

Usually what I observed that connection is unstable and reconnects all the time.  Same ways but connected to a private (not NordVPN) OpenVPN server - no issues.

Saw error "TLS Error: Unroutable control packet received...."

Is there a way to install this script on Android TV?

Has anybody seen issues related to NordVPN/Sony Android TV (I need to be able to stream PS Vue)

Thx!

**Comment by Novocaine85** [comment]
I don't think it's possible since this has been made in python... IMHO I think is better ask directly to Nordvpn to port the Android smartphone app to Android TV. It shouldn't be so hard.

Otherwise (but I did not test on my Nvidia Shield that uses Android TV as well) you should try to install the Android smartphone app using Sideload Launcher, but probably you need mouse and keyboard connected to the TV.
