### ISSUE TITLE
Swap VPN provider?

### ISSUE THREAD

**Issue by devanshuDesai** [jotyGill/openpyn-nordvpn#192]
How difficult would it be to change the VPN provider from NordVPN to something else (ex. PIA)? Also, how do I go about it?

**Comment by jotyGill** [comment]
Doable but would require quite a bit of work (way better than starting from scratch). The main thing is a lot of features such as checking load on servers, finding servers in specific locations, protocol support (tcp, udp) are possible because I found out about the API for NordVPN. If there's no such API some of these won't be possible. Starting point would be finding out if there's an api and what is the naming structure of the config files. for example if the file names are vpn123-udp-us.ovpn, then filenames could be used to workout protocol and country for example. I thought of using some config like 'openpyn-nordvpn/openpyn/config.json' to work with multiple VPN providers.
