### ISSUE TITLE
Rate Limit Exceeded

### ISSUE THREAD

**Issue by larry77** [jotyGill/openpyn-nordvpn#287]
Hello,
Today I got this message when starting openpyn

`
2021-11-17 08:31:34 [ERROR] Error occurred while updating nordvpn.json, rate limit exceeded?
`
Is it anything to worry about? Does it simply mean that nordvpn API got too many requests?
Thanks

**Comment by 1951FDG** [comment]
Hello,

Yes, it means it wasn't able to retrieve the json from the rate limited API, either due to no Internet or too many calls within a specific period of time, this means that it will use the cached copy of the json, the json that was successfully retrieved the last time.

You shouldn't get this error too often, actually almost never since I set 5 min between the calls. But this can also depend on your public IP.

I will make this error a bit more verbose in a future commit.

**Comment by artielange** [comment]
Not sure whats up but I'm still getting rate limited using most recent version
All i ran was:
`sudo openpyn --init`
[entered my credentials and left default for openpyn options]
`openpyn us`
`2022-01-26 10:41:45 [CRITICAL] Cannot GET the JSON from nordvpn.com, Manually Specify a Server using '-s' for example '-s au10'`

**Comment by larry77** [comment]
Hello,
So far the problem has disappeared for me.
