### ISSUE TITLE
Feature ideas

### ISSUE THREAD

**Issue by netgroover** [jotyGill/openpyn-nordvpn#36]
I have a few new feature ideas..

1) Refresh the vpn connection at a predefined time or duration (i.e. in minutes)
2) Auto-restart dropped vpn connection (I have this working well today via openvpn running in systemctl)

I'm happy to fork and have a go myself, but it might take me a while as I don't know Python

**Comment by jotyGill** [comment]
Ideas are welcome. 
Yes, I have been thinking of eventually implementing the "retry on disconnect" function, actually even better "connect to the next server in list, on disconnect", if that would work. As once a server is dropping connection likely it would drop again. 
Btw how are you achieving this, is it the "--connect-retry n" option?

**Comment by netgroover** [comment]
No I am just running openvpn using [systemd](https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units) process control, with the [restart](https://jonarcher.info/2015/08/ensure-systemd-services-restart-on-failure/) option, which seems to be working fine.

As you say though, ideally if the connection has dropped you want to re-connect to the next best host and connect to that one instead.  I don't know if it would be best to use systemd or develop something more advanced.  You could for example perform an intermittent connection/speed test, rather than wait for the vpn to drop, and reconnect if it is below a predefined threshold.  The risk there being that apps/web sites might not be happy that your ip has changed and cause an error?

**Comment by foopex** [comment]
A reconnect on failure would be nice.  My connection occasionally hoses up, and I have to use openpyn -x and then reconnect with my usual string.  And of course, my IP leaks while doing this.

**Comment by Ubermensch85** [comment]
Without daemon option all ok!!!

**Comment by jotyGill** [comment]
@foopex . reconnect at failure has already been implemented. I some times used to receive "SIGTERM[soft,auth-failure]", I added an option to keep trying if that happens (it works). If the connection completely fails and openvpn exits, A connection to the next server in the queue is initiated , then the next and so on.

NordVPN has set the limit of 180 seconds before it would try to reconnect or drop a connection. So when a communication to a vpn server stops, it is going to have to wait at least 180 seconds and I think it tries like 3 times. (180+ 10 wait)* 3 (570 seconds). After that it would actually drop a connection and then "Openpyn" would automatically try the next server.
BTW you only need '-x' if you also need to reapply IPTables rules (you were using '-f'). In that case your IP does not leak. Otherwise you can just use '-k' to kill openvpn.

**Comment by foopex** [comment]
Ok thanks.  I will move to PM if needed I didn't mean to hijack this thread.
