### ISSUE TITLE
Can't find server and connect anymore

### ISSUE THREAD

**Issue by FQsqQ** [jotyGill/openpyn-nordvpn#60]
Hi,

First of all, thank you for this neat piece of code that makes connecting to nordvpn servers a much easier job than with ubuntu's network-manager or else.

It all worked fine so far, but since today I can't connect to any server. Just using openpyn 'country code' command, no option, I always get the message **"There are no servers that satisfy your criteria, please broaden your search."**. Any country code won't work. Any idea why ?

Thanks!

**EDIT : Worked again after doing an 'openpyn --init'.**

**Comment by jotyGill** [comment]
Hi there , Thank you. 

It's suppose to show that error when your search is too specific, (for example --p2p servers in a spefic --area , if none exists in it). If you weren't using any filtering options, likely you weren't able to get json from Nord's API, either because of temporary network issue or their API was briefly down.
