### ISSUE TITLE
Ubuntu, running with sudo makes it crash

### ISSUE THREAD

**Issue by o-l-a-v** [jotyGill/openpyn-nordvpn#66]
Great script you got here, really helps me out with using NordVPN on Linux. Thanks 👍 

Got some bugs though. I'm on Peppermint OS 7, based on Ubuntu 16.04.

There seems to be a difference on running a command with openpyn, with vs without sudo in front of it.
`openpyn -c nl --p2p -t 5 -f`
Will grant for password after saying, "Root access needed to modify 'iptables' rules, and connects just fine
`sudo openpyn -c nl --p2p -t 5 -f`
Asks for root password right away, openpyn does the testing of servers, but after "CONNECTING TO SERVER....." it exits with error:
"FileNotFoundError: [Errno 2] No such file or directory" (Sudo_error.png)
This also happens when logging in to su before running the command. (Su_error.png)

Oh, and one more thing. Exiting would be CTRL-C right? Well, it stops at "SIGNIT[hard,] received, process exiting" and never really exits, have to press CTRL-C again. (Exit_error.png)

Sudo_error
https://user-images.githubusercontent.com/6450056/33093172-85643414-cefc-11e7-8a94-f1fa270bf3a7.PNG

Su_error
https://user-images.githubusercontent.com/6450056/33093171-853f86aa-cefc-11e7-8a8a-8ba7d4aa8031.PNG

Exit_error
https://user-images.githubusercontent.com/6450056/33093163-7ecbf088-cefc-11e7-83db-9f739827f6e6.PNG

**Comment by jotyGill** [comment]
Thanks o-l-a-v, The issue with sudo is the implementation of os.getlogin() function. It doesn't work with all distros. I did except the "FileNotFound" error, it's still in the "test" branch though, not in master yet.
With CTR+C thing, it actually does work, you can press an enter it will open a new line. but yeah I know, it doesn't feel like it's finished just because it doesn't open a new line by itself.
